# override_version.cmake : Find if some environment variables override the current version of the SPOT module.

MACRO(OVERRIDE_IF_DEFINED SOURCEVAR MAKEVAR)
	IF(DEFINED ${MAKEVAR})
		SET(${SOURCEVAR} ${${MAKEVAR}})
		MESSAGE(STATUS "Variable ${SOURCEVAR} has been overriden.")
		MESSAGE(STATUS "\t${SOURCEVAR} : \'${${SOURCEVAR}}\' -> \'${${MAKEVAR}}\'")
	ENDIF()
ENDMACRO()

SET(_SPOT_VERSION_MAJOR 0)
SET(_SPOT_VERSION_MINOR 0)
SET(_SPOT_VERSION_PATCH 5)

OVERRIDE_IF_DEFINED(_SPOT_VERSION_MAJOR SPOT_VERSION_MAJOR_OVERRIDE)
OVERRIDE_IF_DEFINED(_SPOT_VERSION_MINOR SPOT_VERSION_MINOR_OVERRIDE)
OVERRIDE_IF_DEFINED(_SPOT_VERSION_PATCH SPOT_VERSION_PATCH_OVERRIDE)

SET(_SPOT_FULL_VERSION ${_SPOT_VERSION_MAJOR}.${_SPOT_VERSION_MINOR}.${_SPOT_VERSION_PATCH})

IF(DEFINED SPOT_PYTHON_VERSION_OVERRIDE)
	SET(_SPOT_PYTHON_WRAPPER_VERSION ${SPOT_PYTHON_VERSION_OVERRIDE})
ELSE()
	SET(_SPOT_PYTHON_WRAPPER_VERSION ${_SPOT_FULL_VERSION})
ENDIF()
